application: trends-push
runtime: python27
api_version: 1
version: 11
threadsafe: yes

handlers:
- url: /
  static_files: frontend/dist/index.html
  secure: always
  upload: frontend/dist/index\.html

- url: /subscribe
  secure: always
  script: main.app

- url: /unsubscribe
  secure: always
  script: main.app

- url: /send_push
  secure: always
  script: main.app

- url: /endpoints
  secure: always
  script: main.app

- url: /*
  secure: always
  static_dir: frontend/dist/

- url: .*
  secure: always
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"

skip_files:
- ^(.*/)?.*/node_modules/.*$
- ^.git/.*$
- ^(.*/)?.*/frontend/app/.*$